SET IDENTITY_INSERT [dbo].[Answers] ON
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (1, N'44', 16, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (2, N'410', 16, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (3, N'223', 16, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (4, N'224-2', 16, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (6, N'225', 16, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (7, N'413', 16, 1)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (8, N'n-1', 17, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (14, N'n', 17, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (15, N'1', 17, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (16, N'(n-1)/2', 17, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (17, N'n/2', 17, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (18, N'0', 17, 1)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (19, N'2^37', 18, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (20, N'4^19-1', 18, 1)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (21, N'2^38+1 ', 18, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (22, N'2^37+1 ', 18, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (25, N'2^33+1 ', 18, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (26, N'2^39', 18, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (27, N'99', 19, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (28, N'69', 19, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (30, N'51', 19, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (32, N'50', 19, 1)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (33, N'37', 19, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (34, N'34', 19, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (35, N'6', 20, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (36, N'8', 20, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (37, N'9', 20, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (38, N'21', 20, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (39, N'24', 20, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (41, N'30', 20, 1)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (42, N'x = −2', 1, 0)
INSERT INTO [dbo].[Answers] ([IdAnswer], [Answer], [IdQuestion], [isValid]) VALUES (44, N'x = 4', 1, 0)
SET IDENTITY_INSERT [dbo].[Answers] OFF
