SET IDENTITY_INSERT [dbo].[Questions] ON
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (1, N'Math1', N'Probabil ca are')
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (2, N'Math2', N'BENZ era defapt')
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (3, N'Math3', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (4, N'Math4', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (5, N'Math5', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (6, N'Phy1', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (7, N'Phy2', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (8, N'Phy3', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (9, N'Phy4', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (10, N'Phy5', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (11, N'Chem1', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (12, N'Chem2', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (13, N'Chem3', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (14, N'Chem4', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (15, N'Chem5', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (16, N'Prog1', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (17, N'Prog2', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (18, N'Prog3', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (19, N'Prog4', NULL)
INSERT INTO [dbo].[Questions] ([IdQuestion], [Question], [Explanation]) VALUES (20, N'Prog5', NULL)
SET IDENTITY_INSERT [dbo].[Questions] OFF
